
'use client'
import 'app/globals.css'
import {Provider} from 'react-redux';
import { store } from 'redux/store'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <Provider store={store}>
      <html lang="en">
        <body>
            {children}
        </body>
      </html>
    </Provider>
  )
}
