
'use client'
import './globals.css'
import {Provider} from 'react-redux';
import { store } from 'redux/store'
import MenuBar from './components/MenuBar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <Provider store={store}>
      <html lang="en">
        <body>
        <MenuBar />
            {children}
        </body>
      </html>
    </Provider>
  )
}
